name: Build ESM Module

on:
  push:
    branches: [ main, rollup ]
  pull_request: 
    branches: [ main, rollup ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.*

    - name: Clean Cache
      run: yarn cache clean

    - name: Install packages
      run: yarn install

    - name: Build
      run: yarn build

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: cass_knex_cjs
        path: dist
