name: Test Cassandra Knex

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    name: Test Suite

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.*

    - name: Install packages
      run: npm install

    - name: Run tests
      run: npm run test --ci --silent
      env:
        TESTCONTAINERS_RYUK_DISABLED: true
